name: Validate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - "v*"
  pull_request:
    branches:
      - "v*"

jobs:
  validate-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Languages
        run: ./scripts/validateLanguages.sh

  validate-qualities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Qualities
        run: ./scripts/validateQualities.sh
